### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by yogasai** [Linguistics575/neam#16]
in /neam/neam/python/query/wiki.py
line 36, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by adoxography** [comment]
Hi Yosagai,

`requests` is a Python package for handling HTTP requests, and should have been installed during the initial setup. Try installing it manually with `pip install requests` (you may need to use `sudo pip install requests` if you are working on Linux). If you get a permissions error with the latter command, use `source .venv/bin/activate` to get into the virtual environment that would have been set up the first time `neam.sh` was run, then run `pip install requests`. Let me know if you get any errors from those commands.

**Comment by yogasai** [comment]
I installed the package in the virtual environment and when I ran `./neam.sh` (file) I received this error:

[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1045)>
Downloading averaged_perceptron_tagger...
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
[nltk_data]     failed: unable to get local issuer certificate
[nltk_data]     (_ssl.c:1045)>
Downloading universal_tagset...
[nltk_data] Error loading universal_tagset: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1045)>
Skipping loading of user-config.py.

Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:
JVM has been shutdown
<class 'LookupError'>
CRITICAL: Closing network session.

**Comment by adoxography** [comment]
Well that's fun. It looks like your system isn't able to do the SSL checking `NLTK` would like it to do. I've pushed a fix that disables the check, but since I'm not able to reproduce the error on my system, I'm not positive it will fix the issue. Please let me know if it does anything for you.

**Comment by yogasai** [comment]
It worked! Thank you so much!
